# 
# UNIVERSIDAD SERGIO ARBOLEDA
# ESCUELA DE CIENCIAS EXACTAS E INGENIERÍA
# INGENIERÍA DE SISTEMAS Y TELECOMUNICACIONES
# 
# AUTHORS: JUAN JOSÉ MONTENEGRO PULIDO
# EMAILS: juan.montenegro@correo.usa.edu.co
# 
# 20/04/2021
# 

all:
		python3 prueba.py build_ext --inplace
clean:
		rm -rf build *.so *.pyc *.c